import '../models/brand.dart';

const DUMMY_BRANDS = const [
  Brand(
    id: 'b1',
    name: 'BATA',
    percentage: '10%',
    establishedDate: '1970',
    imgUrl: 'bata.png',
    rating: '3',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
  Brand(
    id: 'b2',
    name: 'APEX',
    percentage: '15%',
    establishedDate: '1975',
    imgUrl: 'apex.png',
    rating: '5',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
  Brand(
    id: 'b3',
    name: 'YELLOW',
    percentage: '16%',
    establishedDate: '1961',
    imgUrl: 'yellow.png',
    rating: '4',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
  Brand(
    id: 'b4',
    name: 'COLORS',
    percentage: '20%',
    establishedDate: '1960',
    imgUrl: 'colors.png',
    rating: '5',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
];
const DUMMY_FAVOURITE = const [
  Brand(
    id: 'b5',
    name: 'Sailor',
    percentage: '20%',
    establishedDate: '1979',
    imgUrl: 'sailor.png',
    rating: '5',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
  Brand(
    id: 'b6',
    name: 'Artisan',
    percentage: '10%',
    establishedDate: '1978',
    imgUrl: 'artisan.jpeg',
    rating: '5',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
  Brand(
    id: 'b7',
    name: 'Westics',
    percentage: '20%',
    establishedDate: '1972',
    imgUrl: 'westics.jpeg',
    rating: '5',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
  Brand(
    id: 'b8',
    name: 'Estacy',
    percentage: '30%',
    establishedDate: '1999',
    imgUrl: 'estacy.png',
    rating: '4',
    openingTime: '10;00 am',
    closingTime: '8:00 pm',
  ),
];
